### ISSUE TITLE
Collect First and Last Name while Creating a user account 

### ISSUE THREAD

**Issue by klmnweb** [rtCamp/login-with-google#101]
The plugin does not collect user First and Last name while creating a WP account with the user Google email address. Only the user email is collected.

**Comment by ankitrox** [comment]
Check [this hook](https://github.com/rtCamp/login-with-google/blob/master/src/Utils/Authenticator.php#L104) which provides the entire `user` object from Google which contains information like first name, last name etc. to use it once the user has been created successfully.

In order to keep the plugin minimal, we are not adding any extra information in profile, but plugin has the provision to handle this scenario.

**Comment by klmnweb** [comment]
Thanks @ankitrox . It did work. I am now able to collect the first as well as last name. For others, this is the reference

```
'first_name' => $user->given_name, // get the first name
'last_name' => $user->family_name, // get the last name
```

**Comment by abhishekfdd** [comment]
PR #115 for this is merged. First Name and Last name will be saved in WP profile at the time of registration.
