### ISSUE TITLE
WordPress Login Form Design Seems broken on adding the `Login With Google`

### ISSUE THREAD

**Issue by hbhalodia** [rtCamp/login-with-google#135]
# Issue
- Seems like if we add the `Login with Google` to login form of WordPress, the button seems to be having no spacing below.
- The login button wrapper is added on the `login_form` hook which is present in `wp-login.php` file and present after `password` field and before `remember me` and `submit` button. 

<img width="723" alt="Screenshot 2022-11-25 at 3 43 12 PM" src="https://user-images.githubusercontent.com/58802366/203958920-66a05907-9b87-41b9-9e36-27461fdc2ab3.png">

# Findings
- You can check `wp-login.php` file and find the `login_form` hook and check the plugin how this hook is being called.

# Solution
- Need to add `margin-bottom` around 40px ( same as margin-top and also we can remove top margin ) on the `wp_google_login` class.

**Comment by aviral-mittal** [comment]
@elifvish Can you please taket his up?

**Comment by elifvish** [comment]
Out of the box the button is rendered perfect and looks good. As by default the login with google button is rendered below WP login form bottom padding is not needed, Attached screen shot below of three different sites. 
I was able to reproduce the scenario reported in the issue only in one site and that too on local. Production version of site looks fine.  
As the issue is limited to 1 instance and default behaviour is fine, No action is needed on this.
cc: @aviral-mittal 


<img width="730" alt="Screenshot 2023-01-09 at 2 27 24 PM" src="https://user-images.githubusercontent.com/42698742/211271413-e5333e6c-6906-4368-84ab-7a578fa8717a.png">
<img width="597" alt="Screenshot 2023-01-09 at 1 35 02 PM" src="https://user-images.githubusercontent.com/42698742/211271437-30a779ad-7397-4ebf-8742-6ca10efe9f88.png">
<img width="610" alt="Screenshot 2023-01-09 at 1 32 15 PM" src="https://user-images.githubusercontent.com/42698742/211271470-ebb04b1a-2b06-435c-801d-3993ef72ad0c.png">
