### ISSUE TITLE
Confirm compatibility with WordPress 6.6

### ISSUE THREAD

**Issue by joelabreo227** [rtCamp/login-with-google#178]
## Summary

Confirm compatibility with WordPress 6.6.

### Team
Primary Assignee: @SH4LIN 
PR reviewer: @mchirag2002 
QA: @pavanpatil1  

## References

- https://make.wordpress.org/core/6-6/

## Acceptance Criteria

- As a WordPress user, I can use Login with Google on my site, without any issues
- New features work as expected
- Deprecations are gracefully handled

**Comment by SH4LIN** [comment]
Milestones
- As a WordPress user, I can use Login with Google on my site, without any issues (Done)
- New features work as expected (NA)
- Deprecations are gracefully handled (NA)


@joelabreo227 I have completed the testing of the plugin and it is compatible with the WordPress 6.6. PHP Version is tested up to 8.1. One thing I noticed is that one-tap login isn't working it isn't the WordPress 6.6 issue I have tried using this plugin in WordPress 6.5 One Tap Login still gives me Something went wrong error.

**Comment by pavanpatil1** [comment]
Verified the plugin with WP6.6 and it is working fine. All settings and login functionalities are operating as expected, and the Gutenberg block is functioning properly.

As mentioned above, the one-tap login functionality is not working. However, this issue is not related to WP6.6 and we are tracking it in separate issue. Hence closing this task. 

cc: @joelabreo227
